### ISSUE TITLE
where is coco2012/SegmentationClassAug folder？

### ISSUE THREAD

**Issue by wly-ai-bj** [Reagan1311/ASGNet#10]
how to get the folder of coco2012/SegmentationClassAug?
I download the coco2012 dataset on the internet, but it only has SegmentationClass, without SegmentationClassAug.

**Comment by Reagan1311** [comment]
Hi, SegmentationClassAug is from SBD augmented training data. You can refer to this [link](https://github.com/kazuto1011/deeplab-pytorch/blob/master/data/datasets/voc12/README.md)
