### ISSUE TITLE
View the result in the original image

### ISSUE THREAD

**Issue by Nelebos** [Reagan1311/ASGNet#2]
When I want to view the prediction results of the pictures in the test set, I found that the code I wrote to draw the output results on the original pictures always has bugs and ambiguities. Can I get the code that compares the results in the paper?

When I am performing image inference, the input is the image to be detected and a picture of the target class and its mask picture, then how can I use a picture to quickly detect different pictures, what I actually want to say is: how It is better to detect unknown pictures, not that I can only use one picture for verification.

Hope to provide an idea

**Comment by Reagan1311** [comment]
Hi, the visualization is achieved by adding the transparent segmentation output over the image.
You can visualize the result with matplotlib package: `plt.imshow(image) plt.imshow(mask, alpha=0.3)`

I am a bit confused about your second question. Do you want to use the same support image and test different query samples? If so, you can fix the support feature, and feed the model with different query images.

Hope this helps.

**Comment by Nelebos** [comment]
thanks the reply,
