### ISSUE TITLE
The 5-shot evaluation is problematic

### ISSUE THREAD

**Issue by happycoding1996** [Reagan1311/ASGNet#4]
Hi, thanks for your work.

I have reproduced the 1-shot results that are close to the ones in your paper.

However, when I directly test the model trained with 1-shot in the 5-shot evaluation setting, the result is far from yours.

For example, on fold 0, the 1-shot result is 59.2 and 5-shot I only got 43.73.

Could you help fix this issue?

Thankyou.

**Comment by Reagan1311** [comment]
Sorry for the late reply. The 5-shot results are tested in the model trained with 5-shots.

You may refer to this [paper](https://arxiv.org/abs/1909.11722), it proves directly testing the 1-shot model in prototypical networks will lead to a saturation in 5-shot performance.

**Comment by happycoding1996** [comment]
@Reagan1311 Thank you for your reply!
