### ISSUE TITLE
Category settings in training and testing

### ISSUE THREAD

**Issue by asdnjadsn** [Reagan1311/ASGNet#5]
![微信图片_20210914154940](https://user-images.githubusercontent.com/18710173/133217651-463d4e30-7913-4e2c-aa2a-91ebfbfd7d15.png)
Hello thanks for making the code available.

I have a question. Why are the classes in the configuration file set to 2? These are two specific categories? Or does it have a special meaning?

**Comment by Reagan1311** [comment]
Hi, as this paper focuses on 1/5-shot 1-way segmentation, so the model only predicts two classes (the desired foreground object and background).

**Comment by asdnjadsn** [comment]
I see. Thank you for your reply
