### ISSUE TITLE
how  to prepare the datasets?

### ISSUE THREAD

**Issue by ZhangIceNight** [Reagan1311/ASGNet#6]
Hello, I'm sorry to disturb you, but I am a beginner and I have encountered some problems when preparing the COCO and PASCAL data sets.
1. After I downloaded the VOC2012 data set, I found that there were only about 2000 pictures, but there were more than 5000 data in ASGNet/data/lists/pascal/voc_sbd_merge_noduplicate.txt. And then, I think maybe I should use VOC2012Aug, but there are more than 10000 pictures in VOC2012Aug.
2. I downloaded the COCO data train/test/val in the warehouse link and decompressed them, but I did not find the data label.
I will be very happy if I can get your help, thank you.

**Comment by Reagan1311** [comment]
Hi, sorry for the late reply.
1. Yes, you should use the VOC2012Aug. As the training set of SBD includes part of the VOC 2012 val data, after removing this you will get 5000+ images.
2. You can use this [script](https://mycuhk-my.sharepoint.com/personal/1155122171_link_cuhk_edu_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F1155122171%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2FPFENet%20TPAMI%20Submission%2Fcoco%5Fparse%5Fscript%2Epy&parent=%2Fpersonal%2F1155122171%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2FPFENet%20TPAMI%20Submission&originalPath=aHR0cHM6Ly9teWN1aGstbXkuc2hhcmVwb2ludC5jb20vOnU6L2cvcGVyc29uYWwvMTE1NTEyMjE3MV9saW5rX2N1aGtfZWR1X2hrL0VUa1gxaktWdUpwQWpwUzJkazhYUmhnQnhrT1VyZWdLdjRDN3ppZ3FGWGlFdFE%5FcnRpbWU9ZDQ2UnpyNkYyVWc) to generate data label.

**Comment by ZhangIceNight** [comment]
thank you！！！
